version: '3.8'

services:
  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
    command: ["./pocketbase", "serve", "--http", "0.0.0.0:8090"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - pocketbase